import Course from "../interfaces/Course"
import UserCourse from "../interfaces/UserCourse"
import ManagedCourse from "./ManagedCourse"

// All implementations generated by ChatGPT
class ImplementedCourses {
    static Biology = new (class extends ManagedCourse { constructor() { super({ displayName: "Biologie 🧬", id: "bio" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Chemistry = new (class extends ManagedCourse { constructor() { super({ displayName: "Chemie ⚗️", id: "chem" } as Course, false, false, [true, true, true, true], [], 0.6); } });
    static Physics = new (class extends ManagedCourse { constructor() { super({ displayName: "Physik 🔬", id: "phys" } as Course, false, false, [true, true, true, true], [], 0.6); } });
    static Math = new (class extends ManagedCourse { constructor() { super({ displayName: "Mathe ➗", id: "math" } as Course, false, false, [true, true, true, true], [], 0.7); } });
    static German = new (class extends ManagedCourse { constructor() { super({ displayName: "Deutsch 📚", id: "german" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static English = new (class extends ManagedCourse { constructor() { super({ displayName: "Englisch 🇬🇧", id: "engl" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static French = new (class extends ManagedCourse { constructor() { super({ displayName: "Französisch 🇫🇷", id: "franz" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Spanish = new (class extends ManagedCourse { constructor() { super({ displayName: "Spanisch 🇪🇸", id: "span" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static History = new (class extends ManagedCourse { constructor() { super({ displayName: "Geschichte 🏰", id: "hist" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Geography = new (class extends ManagedCourse { constructor() { super({ displayName: "Geografie 🌍", id: "geo" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Politics = new (class extends ManagedCourse { constructor() { super({ displayName: "Politik 🗳️", id: "pol" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static SocialScience = new (class extends ManagedCourse { constructor() { super({ displayName: "Sozialwissenschaften 🧠", id: "sowi" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Philosophy = new (class extends ManagedCourse { constructor() { super({ displayName: "Philosophie 🤔", id: "phil" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Religion = new (class extends ManagedCourse { constructor() { super({ displayName: "Religion ✝️", id: "reli" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Art = new (class extends ManagedCourse { constructor() { super({ displayName: "Kunst 🎨", id: "art" } as Course, false, false, [true, true, true, true], [], 0.4); } });
    static Music = new (class extends ManagedCourse { constructor() { super({ displayName: "Musik 🎵", id: "music" } as Course, false, false, [true, true, true, true], [], 0.4); } });
    static Sports = new (class extends ManagedCourse { constructor() { super({ displayName: "Sport 🏃", id: "sport" } as Course, false, false, [true, true, true, true], [], 0.3); } });
    static ComputerScience = new (class extends ManagedCourse { constructor() { super({ displayName: "Informatik 💻", id: "cs" } as Course, false, false, [true, true, true, true], [], 0.6); } });
    static Latin = new (class extends ManagedCourse { constructor() { super({ displayName: "Latein 🏛️", id: "latin" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static AncientGreek = new (class extends ManagedCourse { constructor() { super({ displayName: "Altgriechisch 🏺", id: "greek" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Ethics = new (class extends ManagedCourse { constructor() { super({ displayName: "Ethik ⚖️", id: "ethics" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Russian = new (class extends ManagedCourse { constructor() { super({ displayName: "Russisch 🇷🇺", id: "russ" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Italian = new (class extends ManagedCourse { constructor() { super({ displayName: "Italienisch 🇮🇹", id: "ital" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Turkish = new (class extends ManagedCourse { constructor() { super({ displayName: "Türkisch 🇹🇷", id: "turk" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Chinese = new (class extends ManagedCourse { constructor() { super({ displayName: "Chinesisch 🇨🇳", id: "chinese" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Arabic = new (class extends ManagedCourse { constructor() { super({ displayName: "Arabisch 🇸🇦", id: "arabic" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Hebrew = new (class extends ManagedCourse { constructor() { super({ displayName: "Hebräisch 🇮🇱", id: "hebrew" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Japanese = new (class extends ManagedCourse { constructor() { super({ displayName: "Japanisch 🇯🇵", id: "jap" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Polish = new (class extends ManagedCourse { constructor() { super({ displayName: "Polnisch 🇵🇱", id: "polish" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Dutch = new (class extends ManagedCourse { constructor() { super({ displayName: "Niederländisch 🇳🇱", id: "dutch" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Danish = new (class extends ManagedCourse { constructor() { super({ displayName: "Dänisch 🇩🇰", id: "danish" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Drama = new (class extends ManagedCourse { constructor() { super({ displayName: "Darstellendes Spiel 🎭", id: "drama" } as Course, false, false, [true, true, true, true], [], 0.4); } });
    static Pedagogy = new (class extends ManagedCourse { constructor() { super({ displayName: "Pädagogik 👶", id: "paed" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Psychology = new (class extends ManagedCourse { constructor() { super({ displayName: "Psychologie 🧠", id: "psy" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Economics = new (class extends ManagedCourse { constructor() { super({ displayName: "Wirtschaft 💼", id: "econ" } as Course, false, false, [true, true, true, true], [], 0.6); } });
    static Engineering = new (class extends ManagedCourse { constructor() { super({ displayName: "Technik 🛠️", id: "tech" } as Course, false, false, [true, true, true, true], [], 0.6); } });
    static Law = new (class extends ManagedCourse { constructor() { super({ displayName: "Rechtskunde 📜", id: "law" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Astronomy = new (class extends ManagedCourse { constructor() { super({ displayName: "Astronomie 🔭", id: "astro" } as Course, false, false, [true, true, true, true], [], 0.6); } });
    static Literature = new (class extends ManagedCourse { constructor() { super({ displayName: "Literatur ✍️", id: "lit" } as Course, false, false, [true, true, true, true], [], 0.4); } });
    static MediaStudies = new (class extends ManagedCourse { constructor() { super({ displayName: "Medienkunde 📰", id: "media" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Nutrition = new (class extends ManagedCourse { constructor() { super({ displayName: "Ernährungslehre 🥗", id: "nutri" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static HomeEconomics = new (class extends ManagedCourse { constructor() { super({ displayName: "Hauswirtschaft 🍳", id: "hausw" } as Course, false, false, [true, true, true, true], [], 0.4); } });
    static TextileDesign = new (class extends ManagedCourse { constructor() { super({ displayName: "Textilgestaltung 🧵", id: "textil" } as Course, false, false, [true, true, true, true], [], 0.4); } });
    static Crafts = new (class extends ManagedCourse { constructor() { super({ displayName: "Werken 🔨", id: "werken" } as Course, false, false, [true, true, true, true], [], 0.4); } });
    static NwT = new (class extends ManagedCourse { constructor() { super({ displayName: "Naturwissenschaft & Technik 🔧", id: "nwt" } as Course, false, false, [true, true, true, true], [], 0.6); } });
    static AES = new (class extends ManagedCourse { constructor() { super({ displayName: "Alltagskultur, Ernährung, Soziales 🧺", id: "aes" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static WBS = new (class extends ManagedCourse { constructor() { super({ displayName: "Wirtschaft, Berufs- & Studienorientierung 🎯", id: "wbs" } as Course, false, false, [true, true, true, true], [], 0.4); } });
    static LER = new (class extends ManagedCourse { constructor() { super({ displayName: "LER: Lebensgestaltung–Ethik–Religionskunde 🕊️", id: "ler" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static DaZ = new (class extends ManagedCourse { constructor() { super({ displayName: "Deutsch als Zweitsprache (DaZ) 🗣️", id: "daz" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Robotics = new (class extends ManagedCourse { constructor() { super({ displayName: "Robotik 🤖", id: "robot" } as Course, false, false, [true, true, true, true], [], 0.6); } });
    static BusinessInformatics = new (class extends ManagedCourse { constructor() { super({ displayName: "Wirtschaftsinformatik 💻", id: "wi" } as Course, false, false, [true, true, true, true], [], 0.6); } });
    static Seminar = new (class extends ManagedCourse { constructor() { super({ displayName: "Seminarfach 📑", id: "seminar" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static ProjectCourse = new (class extends ManagedCourse { constructor() { super({ displayName: "Projektkurs 🧩", id: "proj" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static ModernGreek = new (class extends ManagedCourse { constructor() { super({ displayName: "Neugriechisch 🇬🇷", id: "neugr" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Portuguese = new (class extends ManagedCourse { constructor() { super({ displayName: "Portugiesisch 🇵🇹", id: "port" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Swedish = new (class extends ManagedCourse { constructor() { super({ displayName: "Schwedisch 🇸🇪", id: "swed" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Norwegian = new (class extends ManagedCourse { constructor() { super({ displayName: "Norwegisch 🇳🇴", id: "nor" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Czech = new (class extends ManagedCourse { constructor() { super({ displayName: "Tschechisch 🇨🇿", id: "czech" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Ukrainian = new (class extends ManagedCourse { constructor() { super({ displayName: "Ukrainisch 🇺🇦", id: "ukr" } as Course, false, false, [true, true, true, true], [], 0.5); } });

    static getNewTemplate = () => new (class extends ManagedCourse { constructor() { super({ displayName: "Neuer Kurs", id: "new_course" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static isEqualToTemplate = (course: ManagedCourse) : boolean => {
        return course.course.id === "new_course" && course.course.displayName === "Neuer Kurs" && !course.isLK && !course.isOralExamCourse && course.takesPartInQuarters.every(q => q) && course.writtenWeightPercantage === 0.5;
    }

    public static readonly Implementations = [
        ImplementedCourses.Biology,
        ImplementedCourses.Chemistry,
        ImplementedCourses.Physics,
        ImplementedCourses.Math,
        ImplementedCourses.German,
        ImplementedCourses.English,
        ImplementedCourses.French,
        ImplementedCourses.Spanish,
        ImplementedCourses.History,
        ImplementedCourses.Geography,
        ImplementedCourses.Politics,
        ImplementedCourses.SocialScience,
        ImplementedCourses.Philosophy,
        ImplementedCourses.Religion,
        ImplementedCourses.Art,
        ImplementedCourses.Music,
        ImplementedCourses.Sports,
        ImplementedCourses.ComputerScience,
        ImplementedCourses.Latin,
        ImplementedCourses.AncientGreek,
        ImplementedCourses.Ethics,
        ImplementedCourses.Russian,
        ImplementedCourses.Italian,
        ImplementedCourses.Turkish,
        ImplementedCourses.Chinese,
        ImplementedCourses.Arabic,
        ImplementedCourses.Hebrew,
        ImplementedCourses.Japanese,
        ImplementedCourses.Polish,
        ImplementedCourses.Dutch,
        ImplementedCourses.Danish,
        ImplementedCourses.Drama,
        ImplementedCourses.Pedagogy,
        ImplementedCourses.Psychology,
        ImplementedCourses.Economics,
        ImplementedCourses.Engineering,
        ImplementedCourses.Law,
        ImplementedCourses.Astronomy,
        ImplementedCourses.Literature,
        ImplementedCourses.MediaStudies,
        ImplementedCourses.Nutrition,
        ImplementedCourses.HomeEconomics,
        ImplementedCourses.TextileDesign,
        ImplementedCourses.Crafts,
        ImplementedCourses.NwT,
        ImplementedCourses.AES,
        ImplementedCourses.WBS,
        ImplementedCourses.LER,
        ImplementedCourses.DaZ,
        ImplementedCourses.Robotics,
        ImplementedCourses.BusinessInformatics,
        ImplementedCourses.Seminar,
        ImplementedCourses.ProjectCourse,
        ImplementedCourses.ModernGreek,
        ImplementedCourses.Portuguese,
        ImplementedCourses.Swedish,
        ImplementedCourses.Norwegian,
        ImplementedCourses.Czech,
        ImplementedCourses.Ukrainian, 
    ];
}

export default ImplementedCourses;