import Course from "../interfaces/Course"
import UserCourse from "../interfaces/UserCourse"
import ManagedCourse from "./ManagedCourse"

// All implementations generated by ChatGPT
class ImplementedCourses {
    static Biology = new (class extends ManagedCourse { constructor() { super({ displayName: "Biologie 🧬", id: "bio" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Chemistry = new (class extends ManagedCourse { constructor() { super({ displayName: "Chemie ⚗️", id: "chem" } as Course, false, false, [true, true, true, true], [], 0.6); } });
    static Physics = new (class extends ManagedCourse { constructor() { super({ displayName: "Physik 🔬", id: "phys" } as Course, false, false, [true, true, true, true], [], 0.6); } });
    static Math = new (class extends ManagedCourse { constructor() { super({ displayName: "Mathe ➗", id: "math" } as Course, false, false, [true, true, true, true], [], 0.7); } });
    static German = new (class extends ManagedCourse { constructor() { super({ displayName: "Deutsch 📚", id: "german" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static English = new (class extends ManagedCourse { constructor() { super({ displayName: "Englisch 🇬🇧", id: "engl" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static French = new (class extends ManagedCourse { constructor() { super({ displayName: "Französisch 🇫🇷", id: "franz" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Spanish = new (class extends ManagedCourse { constructor() { super({ displayName: "Spanisch 🇪🇸", id: "span" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static History = new (class extends ManagedCourse { constructor() { super({ displayName: "Geschichte 🏰", id: "hist" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Geography = new (class extends ManagedCourse { constructor() { super({ displayName: "Geografie 🌍", id: "geo" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Politics = new (class extends ManagedCourse { constructor() { super({ displayName: "Politik 🗳️", id: "pol" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static SocialScience = new (class extends ManagedCourse { constructor() { super({ displayName: "Sozialwissenschaften 🧠", id: "sowi" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Philosophy = new (class extends ManagedCourse { constructor() { super({ displayName: "Philosophie 🤔", id: "phil" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Religion = new (class extends ManagedCourse { constructor() { super({ displayName: "Religion ✝️", id: "reli" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Art = new (class extends ManagedCourse { constructor() { super({ displayName: "Kunst 🎨", id: "art" } as Course, false, false, [true, true, true, true], [], 0.4); } });
    static Music = new (class extends ManagedCourse { constructor() { super({ displayName: "Musik 🎵", id: "music" } as Course, false, false, [true, true, true, true], [], 0.4); } });
    static Sports = new (class extends ManagedCourse { constructor() { super({ displayName: "Sport 🏃", id: "sport" } as Course, false, false, [true, true, true, true], [], 0.3); } });
    static ComputerScience = new (class extends ManagedCourse { constructor() { super({ displayName: "Informatik 💻", id: "cs" } as Course, false, false, [true, true, true, true], [], 0.6); } });
    static Latin = new (class extends ManagedCourse { constructor() { super({ displayName: "Latein 🏛️", id: "latin" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static AncientGreek = new (class extends ManagedCourse { constructor() { super({ displayName: "Altgriechisch 🏺", id: "greek" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Ethics = new (class extends ManagedCourse { constructor() { super({ displayName: "Ethik ⚖️", id: "ethics" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Russian = new (class extends ManagedCourse { constructor() { super({ displayName: "Russisch 🇷🇺", id: "russ" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Italian = new (class extends ManagedCourse { constructor() { super({ displayName: "Italienisch 🇮🇹", id: "ital" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Turkish = new (class extends ManagedCourse { constructor() { super({ displayName: "Türkisch 🇹🇷", id: "turk" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Chinese = new (class extends ManagedCourse { constructor() { super({ displayName: "Chinesisch 🇨🇳", id: "chinese" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Arabic = new (class extends ManagedCourse { constructor() { super({ displayName: "Arabisch 🇸🇦", id: "arabic" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Hebrew = new (class extends ManagedCourse { constructor() { super({ displayName: "Hebräisch 🇮🇱", id: "hebrew" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Japanese = new (class extends ManagedCourse { constructor() { super({ displayName: "Japanisch 🇯🇵", id: "jap" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Polish = new (class extends ManagedCourse { constructor() { super({ displayName: "Polnisch 🇵🇱", id: "polish" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Dutch = new (class extends ManagedCourse { constructor() { super({ displayName: "Niederländisch 🇳🇱", id: "dutch" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Danish = new (class extends ManagedCourse { constructor() { super({ displayName: "Dänisch 🇩🇰", id: "danish" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Drama = new (class extends ManagedCourse { constructor() { super({ displayName: "Darstellendes Spiel 🎭", id: "drama" } as Course, false, false, [true, true, true, true], [], 0.4); } });
    static Pedagogy = new (class extends ManagedCourse { constructor() { super({ displayName: "Pädagogik 👶", id: "paed" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Psychology = new (class extends ManagedCourse { constructor() { super({ displayName: "Psychologie 🧠", id: "psy" } as Course, false, false, [true, true, true, true], [], 0.5); } });
    static Economics = new (class extends ManagedCourse { constructor() { super({ displayName: "Wirtschaft 💼", id: "econ" } as Course, false, false, [true, true, true, true], [], 0.6); } });
    static Engineering = new (class extends ManagedCourse { constructor() { super({ displayName: "Technik 🛠️", id: "tech" } as Course, false, false, [true, true, true, true], [], 0.6); } });
    static Law = new (class extends ManagedCourse { constructor() { super({ displayName: "Rechtskunde 📜", id: "law" } as Course, false, false, [true, true, true, true], [], 0.5); } });

    static Implementations = [
        ImplementedCourses.Biology,
        ImplementedCourses.Chemistry,
        ImplementedCourses.Physics,
        ImplementedCourses.Math,
        ImplementedCourses.German,
        ImplementedCourses.English,
        ImplementedCourses.French,
        ImplementedCourses.Spanish,
        ImplementedCourses.History,
        ImplementedCourses.Geography,
        ImplementedCourses.Politics,
        ImplementedCourses.SocialScience,
        ImplementedCourses.Philosophy,
        ImplementedCourses.Religion,
        ImplementedCourses.Art,
        ImplementedCourses.Music,
        ImplementedCourses.Sports,
        ImplementedCourses.ComputerScience,
        ImplementedCourses.Latin,
        ImplementedCourses.AncientGreek,
        ImplementedCourses.Ethics,
        ImplementedCourses.Russian,
        ImplementedCourses.Italian,
        ImplementedCourses.Turkish,
        ImplementedCourses.Chinese,
        ImplementedCourses.Arabic,
        ImplementedCourses.Hebrew,
        ImplementedCourses.Japanese,
        ImplementedCourses.Polish,
        ImplementedCourses.Dutch,
        ImplementedCourses.Danish,
        ImplementedCourses.Drama,
        ImplementedCourses.Pedagogy,
        ImplementedCourses.Psychology,
        ImplementedCourses.Economics,
        ImplementedCourses.Engineering,
        ImplementedCourses.Law
    ];
}
