import Course from "../interfaces/Course"
import UserCourse from "../interfaces/UserCourse"
import { ManagedCourse } from "./ManagedCourse"

// All implementations generated by ChatGPT
class ImplementedCourses {
    // I – sprachlich-literarisch-künstlerisch
    static Deutsch = new (class extends ManagedCourse { constructor() { super({ displayName: "📚 Deutsch", id: "deutsch" } as Course, false, false, [true, true, true, true], [], 0.7, 'I'); } })();
    static Englisch = new (class extends ManagedCourse { constructor() { super({ displayName: "🇬🇧 Englisch", id: "englisch" } as Course, false, false, [true, true, true, true], [], 0.7, 'I'); } })();
    static Franzoesisch = new (class extends ManagedCourse { constructor() { super({ displayName: "🇫🇷 Französisch", id: "franzoesisch" } as Course, false, false, [true, true, true, true], [], 0.7, 'I'); } })();
    static Latein = new (class extends ManagedCourse { constructor() { super({ displayName: "🏛️ Latein", id: "latein" } as Course, false, false, [true, true, true, true], [], 0.7, 'I'); } })();
    static Griechisch = new (class extends ManagedCourse { constructor() { super({ displayName: "🇬🇷 Griechisch", id: "griechisch" } as Course, false, false, [true, true, true, true], [], 0.7, 'I'); } })();
    static Russisch = new (class extends ManagedCourse { constructor() { super({ displayName: "🇷🇺 Russisch", id: "russisch" } as Course, false, false, [true, true, true, true], [], 0.7, 'I'); } })();
    static Spanisch = new (class extends ManagedCourse { constructor() { super({ displayName: "🇪🇸 Spanisch", id: "spanisch" } as Course, false, false, [true, true, true, true], [], 0.7, 'I'); } })();
    static Italienisch = new (class extends ManagedCourse { constructor() { super({ displayName: "🇮🇹 Italienisch", id: "italienisch" } as Course, false, false, [true, true, true, true], [], 0.7, 'I'); } })();
    static Portugiesisch = new (class extends ManagedCourse { constructor() { super({ displayName: "🇵🇹 Portugiesisch", id: "portugiesisch" } as Course, false, false, [true, true, true, true], [], 0.7, 'I'); } })();
    static Chinesisch = new (class extends ManagedCourse { constructor() { super({ displayName: "🇨🇳 Chinesisch", id: "chinesisch" } as Course, false, false, [true, true, true, true], [], 0.7, 'I'); } })();
    static Hebraeisch = new (class extends ManagedCourse { constructor() { super({ displayName: "🇮🇱 Hebräisch", id: "hebraeisch" } as Course, false, false, [true, true, true, true], [], 0.7, 'I'); } })();
    static Japanisch = new (class extends ManagedCourse { constructor() { super({ displayName: "🇯🇵 Japanisch", id: "japanisch" } as Course, false, false, [true, true, true, true], [], 0.7, 'I'); } })();
    static Tuerkisch = new (class extends ManagedCourse { constructor() { super({ displayName: "🇹🇷 Türkisch", id: "tuerkisch" } as Course, false, false, [true, true, true, true], [], 0.7, 'I'); } })();

    static Musik = new (class extends ManagedCourse { constructor() { super({ displayName: "🎵 Musik", id: "musik" } as Course, false, false, [true, true, true, true], [], 0.3, 'I'); } })();
    static BildendeKunst = new (class extends ManagedCourse { constructor() { super({ displayName: "🎨 Bildende Kunst", id: "bildende_kunst" } as Course, false, false, [true, true, true, true], [], 0.3, 'I'); } })();

    static VertiefungskursSprache = new (class extends ManagedCourse { constructor() { super({ displayName: "🗣️ Vertiefungskurs Sprache", id: "vertiefungskurs_sprache" } as Course, false, false, [true, true, true, true], [], 0.5, 'I'); } })();
    static Literatur = new (class extends ManagedCourse { constructor() { super({ displayName: "📖 Literatur", id: "literatur" } as Course, false, false, [true, true, true, true], [], 0.5, 'I'); } })();
    static LiteraturUndTheater = new (class extends ManagedCourse { constructor() { super({ displayName: "🎭 Literatur und Theater", id: "literatur_und_theater" } as Course, false, false, [true, true, true, true], [], 0.3, 'I'); } })();

    // II – gesellschaftswissenschaftlich
    static Geschichte = new (class extends ManagedCourse { constructor() { super({ displayName: "📜 Geschichte", id: "geschichte" } as Course, false, false, [true, true, true, true], [], 0.5, 'II'); } })();
    static Geographie = new (class extends ManagedCourse { constructor() { super({ displayName: "🗺️ Geographie", id: "geographie" } as Course, false, false, [true, true, true, true], [], 0.5, 'II'); } })();
    static Gemeinschaftskunde = new (class extends ManagedCourse { constructor() { super({ displayName: "🧑‍🤝‍🧑 Gemeinschaftskunde", id: "gemeinschaftskunde" } as Course, false, false, [true, true, true, true], [], 0.5, 'II'); } })();
    static Wirtschaft = new (class extends ManagedCourse { constructor() { super({ displayName: "💼 Wirtschaft", id: "wirtschaft" } as Course, false, false, [true, true, true, true], [], 0.5, 'II'); } })();
    static Religionslehre = new (class extends ManagedCourse { constructor() { super({ displayName: "🛐 Religionslehre", id: "religionslehre" } as Course, false, false, [true, true, true, true], [], 0.4, 'II'); } })();
    static Ethik = new (class extends ManagedCourse { constructor() { super({ displayName: "⚖️ Ethik", id: "ethik" } as Course, false, false, [true, true, true, true], [], 0.4, 'II'); } })();

    static Philosophie = new (class extends ManagedCourse { constructor() { super({ displayName: "🤔 Philosophie", id: "philosophie" } as Course, false, false, [true, true, true, true], [], 0.5, 'II'); } })();
    static Psychologie = new (class extends ManagedCourse { constructor() { super({ displayName: "🧠 Psychologie", id: "psychologie" } as Course, false, false, [true, true, true, true], [], 0.5, 'II'); } })();

    // III – mathematisch-naturwissenschaftlich-technisch
    static Mathematik = new (class extends ManagedCourse { constructor() { super({ displayName: "➗ Mathematik", id: "mathematik" } as Course, false, false, [true, true, true, true], [], 0.7, 'III'); } })();
    static Biologie = new (class extends ManagedCourse { constructor() { super({ displayName: "🧬 Biologie", id: "biologie" } as Course, false, false, [true, true, true, true], [], 0.6, 'III'); } })();
    static Chemie = new (class extends ManagedCourse { constructor() { super({ displayName: "🧪 Chemie", id: "chemie" } as Course, false, false, [true, true, true, true], [], 0.6, 'III'); } })();
    static Physik = new (class extends ManagedCourse { constructor() { super({ displayName: "⚡ Physik", id: "physik" } as Course, false, false, [true, true, true, true], [], 0.6, 'III'); } })();
    static NwT = new (class extends ManagedCourse { constructor() { super({ displayName: "🛠️ Naturwissenschaft und Technik (NwT)", id: "nwt" } as Course, false, false, [true, true, true, true], [], 0.5, 'III'); } })();
    static Informatik = new (class extends ManagedCourse { constructor() { super({ displayName: "💻 Informatik", id: "informatik" } as Course, false, false, [true, true, true, true], [], 0.6, 'III'); } })();

    static VertiefungskursMathematik = new (class extends ManagedCourse { constructor() { super({ displayName: "➕ Vertiefungskurs Mathematik", id: "vertiefungskurs_mathematik" } as Course, false, false, [true, true, true, true], [], 0.7, 'III'); } })();
    static DarstellendeGeometrie = new (class extends ManagedCourse { constructor() { super({ displayName: "📐 Darstellende Geometrie", id: "darstellende_geometrie" } as Course, false, false, [true, true, true, true], [], 0.6, 'III'); } })();
    static DigitaleMathematischeWerkzeuge = new (class extends ManagedCourse { constructor() { super({ displayName: "🧮 Digitale mathematische Werkzeuge", id: "digitale_mathematische_werkzeuge" } as Course, false, false, [true, true, true, true], [], 0.4, 'III'); } })();
    static Astronomie = new (class extends ManagedCourse { constructor() { super({ displayName: "🌌 Astronomie", id: "astronomie" } as Course, false, false, [true, true, true, true], [], 0.6, 'III'); } })();
    static Geologie = new (class extends ManagedCourse { constructor() { super({ displayName: "🪨 Geologie", id: "geologie" } as Course, false, false, [true, true, true, true], [], 0.6, 'III'); } })();

    // Ohne Zuordnung
    static Sport = new (class extends ManagedCourse { constructor() { super({ displayName: "🏃‍♂️ Sport", id: "sport" } as Course, false, false, [true, true, true, true], [], 0.2, 'Sports'); } })();

    static getNewTemplate = () => new (class extends ManagedCourse { constructor() { super({ displayName: "Neuer Kurs", id: "new_course" } as Course, false, false, [true, true, true, true], [], 0.5, 'I'); } });
    static isEqualToTemplate = (course: ManagedCourse) : boolean => {
        return course.course.id === "new_course" && course.course.displayName === "Neuer Kurs" && !course.isLK && !course.isOralExamCourse && course.takesPartInQuarters.every(q => q) && course.writtenWeightPercantage === 0.5;
    }

    public static readonly Implementations = [
        ImplementedCourses.Deutsch,
        ImplementedCourses.Englisch,
        ImplementedCourses.Franzoesisch,
        ImplementedCourses.Latein,
        ImplementedCourses.Griechisch,
        ImplementedCourses.Russisch,
        ImplementedCourses.Spanisch,
        ImplementedCourses.Italienisch,
        ImplementedCourses.Portugiesisch,
        ImplementedCourses.Chinesisch,
        ImplementedCourses.Hebraeisch,
        ImplementedCourses.Japanisch,
        ImplementedCourses.Tuerkisch,

        ImplementedCourses.Musik,
        ImplementedCourses.BildendeKunst,
        ImplementedCourses.VertiefungskursSprache,
        ImplementedCourses.Literatur,
        ImplementedCourses.LiteraturUndTheater,

        ImplementedCourses.Geschichte,
        ImplementedCourses.Geographie,
        ImplementedCourses.Gemeinschaftskunde,
        ImplementedCourses.Wirtschaft,
        ImplementedCourses.Religionslehre,
        ImplementedCourses.Ethik,
        ImplementedCourses.Philosophie,
        ImplementedCourses.Psychologie,

        ImplementedCourses.Mathematik,
        ImplementedCourses.Biologie,
        ImplementedCourses.Chemie,
        ImplementedCourses.Physik,
        ImplementedCourses.NwT,
        ImplementedCourses.Informatik,
        ImplementedCourses.VertiefungskursMathematik,
        ImplementedCourses.DarstellendeGeometrie,
        ImplementedCourses.DigitaleMathematischeWerkzeuge,
        ImplementedCourses.Astronomie,
        ImplementedCourses.Geologie,

        ImplementedCourses.Sport,
    ];
}

export default ImplementedCourses;